hl.bind("SUPER + ALT + Up", actions.workspace.focus("prev"))
hl.bind("SUPER + ALT + Down", actions.workspace.focus("next"))

hl.bind("SUPER + ALT + Home", actions.workspace.focus("home"))
hl.bind("SUPER + ALT + End", actions.workspace.focus("last"))

hl.bind("SUPER + ALT + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind("SUPER + ALT + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind("SUPER + ALT + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind("SUPER + ALT + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind("SUPER + ALT + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind("SUPER + ALT + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind("SUPER + ALT + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind("SUPER + ALT + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind("SUPER + ALT + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind("SUPER + ALT + A", hl.dsp.focus({ workspace = 10 }))
hl.bind("SUPER + ALT + B", hl.dsp.focus({ workspace = 11 }))
hl.bind("SUPER + ALT + C", hl.dsp.focus({ workspace = 12 }))
hl.bind("SUPER + ALT + D", hl.dsp.focus({ workspace = 13 }))
hl.bind("SUPER + ALT + E", hl.dsp.focus({ workspace = 14 }))
hl.bind("SUPER + ALT + F", hl.dsp.focus({ workspace = 15 }))
hl.bind("SUPER + ALT + 0", hl.dsp.focus({ workspace = 16 }))
