return {
	"stevearc/conform.nvim",
	event = { "BufWritePre" },
	cmd = { "ConformInfo" },
	opts = {
		notify_on_error = true,
		format_on_save = { async = false },
		default_format_opts = {
			lsp_format = "fallback",
			timeout_ms = 1000,
			stop_after_first = true,
		},
		formatters = {
			prettierd = { require_cwd = true },
		},
		formatters_by_ft = {
			bash = { "shfmt" },
			c = { "clang-format" },
			cpp = { "clang-format" },
			css = { "prettierd", "prettier" },
			elixir = { "mix" },
			go = { "gofmt", "goimports" },
			graphql = { "prettierd", "prettier" },
			html = { "prettierd", "prettier" },
			java = { "google-java-format" },
			javascript = { "prettierd", "prettier" },
			javascriptreact = { "prettierd", "prettier" },
			json = { "prettierd", "prettier" },
			jsonc = { "prettierd", "prettier" },
			kotlin = { "ktlint" },
			less = { "prettierd", "prettier" },
			lua = { "stylua" },
			markdown = { "prettierd", "prettier" },
			php = { "php-cs-fixer" },
			python = { "black", "isort" },
			ruby = { "rubocop" },
			rust = { "rustfmt" },
			scss = { "prettierd", "prettier" },
			sh = { "shfmt" },
			swift = { "swiftformat" },
			toml = { "taplo" },
			typescript = { "prettierd", "prettier" },
			typescriptreact = { "prettierd", "prettier" },
			vue = { "prettierd", "prettier" },
			xml = { "prettierd", "prettier" },
			yaml = { "prettierd", "prettier" },
		},
	},
}
