local prettier = { "prettierd", "prettier" }

return {
	"stevearc/conform.nvim",
	event = "BufWritePre",
	cmd = "ConformInfo",
	opts = {
		notify_on_error = false,
		format_on_save = {
			lsp_format = "fallback",
			timeout_ms = 2000,
		},
		default_format_opts = {
			stop_after_first = true,
		},
		formatters = {
			prettierd = {
				require_cwd = true,
			},
		},
		formatters_by_ft = {
			bash = { "shfmt" },
			c = { "clang-format" },
			cpp = { "clang-format" },
			css = prettier,
			elixir = { "mix" },
			go = { "goimports" },
			graphql = prettier,
			html = prettier,
			java = { "google-java-format" },
			javascript = prettier,
			javascriptreact = prettier,
			json = prettier,
			jsonc = prettier,
			kotlin = { "ktlint" },
			less = prettier,
			lua = { "stylua" },
			markdown = prettier,
			markdown_inline = prettier,
			php = { "php-cs-fixer" },
			python = { "isort", "black" },
			ruby = { "rubocop" },
			rust = { "rustfmt" },
			scss = prettier,
			sh = { "shfmt" },
			swift = { "swiftformat" },
			toml = { "taplo" },
			typescript = prettier,
			typescriptreact = prettier,
			vue = prettier,
			xml = prettier,
			yaml = prettier,
		},
	},
}
