return {
	"windwp/nvim-autopairs",
	event = "InsertEnter",
	opts = {
		check_ts = true,
		ts_config = {
			lua = { "string" },
			javascript = { "template_string" },
			javascriptreact = { "template_string" },
			typescript = { "template_string" },
			typescriptreact = { "template_string" },
		},
		disable_filetype = {
			"TelescopePrompt",
			"lazy",
			"mason",
			"neo-tree",
			"spectre_panel",
		},
		disable_in_macro = true,
		enable_check_bracket_line = false,
		ignored_next_char = "[%w%%%'%[%'%\"]",
		fast_wrap = {
			map = "<M-e>",
			chars = { "{", "[", "(", '"', "'" },
			pattern = [=[[%'%"%)%>%]%)%}%,]]=],
			offset = -1,
			end_key = "$",
			keys = "qwertyuiopasdfghjklzxcvbnm",
			check_comma = true,
			highlight = "Search",
			highlight_grey = "Comment",
		},
	},
}
