exec-once = hyprpm reload
exec-once = waypaper --random
exec-once = waybar
exec-once = systemctl --user start histuid
exec-once = elephant
exec-once = waycorner
exec-once = hypridle

exec-once = [workspace special:stylus silent] flatpak run com.github.flxzt.rnote
exec-once = [workspace special:radio silent] shortwave
