exec-once = hyprpm reload
exec-once = waybar
exec-once = systemctl --user start histuid
exec-once = elephant
exec-once = hypridle
exec-once = waypaper --random
exec-once = solaar --window=hide
exec-once = hyprmousetrap

exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

exec-once = [workspace special:stylus silent] flatpak run com.github.flxzt.rnote
exec-once = [workspace special:radio silent] shortwave
