bind = $modifier, 1, exec, kitty
bind = $modifier CTRL, 1, exec, kitty su

bind = $modifier, 2, exec, nautilus

bind = $modifier, 3, exec, firefox
bind = $modifier CTRL, 3, exec, firefox --private-window

