bind = $modifier, 1, exec, kitty
bind = $modifier ALT, 1, exec, kitty su

bind = $modifier, 2, exec, nautilus

bind = $modifier, 3, exec, firefox
bind = $modifier ALT, 3, exec, firefox --private-window

bind = $modifier, 4, exec, firefox https://app.todoist.com
bind = $modifier, 5, exec, obsidian

bind = $modifier, 6, exec, flatpak run com.github.flxzt.rnote

