bindr = $modifier, 1, exec, kitty
bindr = $modifier CTRL, 1, exec, kitty su

bindr = $modifier, 2, exec, nautilus

bindr = $modifier, 3, exec, firefox
bindr = $modifier CTRL, 3, exec, firefox --private-window

bindr = $modifier, 4, exec, obsidian

bindr = $modifier, F4, exec, waypaper
bindr = $modifier, F5, exec, gnome-calculator
bindr = $modifier, F6, exec, dialect
bindr = $modifier, F7, exec, gnome-characters
bindr = $modifier, F8, exec, $script/screenshot
bindr = $modifier, F9, exec, eyedropper
