binde = , $brightnessDown, exec, brightnessctl set 5%-
binde = , $brightnessUp, exec, brightnessctl set +5%

binde = ALT, $brightnessDown, exec, brightnessctl set 1%-
binde = ALT, $brightnessUp, exec, brightnessctl set +1%

binde = CTRL, $brightnessDown, exec, brightnessctl set 1%
binde = CTRL, $brightnessUp, exec, brightnessctl set 100%
