binde = , XF86MonBrightnessDown, exec, brightnessctl set 5%-
binde = , XF86MonBrightnessUp, exec, brightnessctl set +5%

binde = ALT, XF86MonBrightnessDown, exec, brightnessctl set 1%-
binde = ALT, XF86MonBrightnessUp, exec, brightnessctl set +1%

binde = SHIFT, XF86MonBrightnessDown, exec, brightnessctl set 1%
binde = SHIFT, XF86MonBrightnessUp, exec, brightnessctl set 100%
