binde = , $brightnessDown, exec, brightnessctl set 5%-
binde = , $brightnessUp, exec, brightnessctl set +5%

binde = $alternateLeft, $brightnessDown, exec, brightnessctl set 1%-
binde = $alternateLeft, $brightnessUp, exec, brightnessctl set +1%

binde = $controlLeft, $brightnessDown, exec, brightnessctl set 1%
binde = $controlLeft, $brightnessUp, exec, brightnessctl set 100%
