bind = $modifier, Escape, exec, killall waybar || waybar

bind = $modifier, Menu, exec, walker
bind = , XF86Search, exec, walker

bind = $modifier CTRL ALT, D, exec, $script/set-theme
bind = $modifier CTRL ALT, C, exec, $script/set-theme cartoon
bind = $modifier CTRL ALT, F, exec, $script/set-theme focus
bind = $modifier CTRL ALT, V, exec, $script/set-theme void

bind = $modifier ALT, W, exec, $script/set-paper image
bind = $modifier ALT, V, exec, $script/set-paper video
bind = $modifier ALT, B, exec, $script/set-paper off
