binde = $modifier, XF86AudioPlay, exec, $script/set-sunset toggle

binde = $modifier, XF86AudioLowerVolume, exec, $script/set-shader prev
binde = $modifier, XF86AudioMute, exec, $script/set-shader off
binde = $modifier, XF86AudioRaiseVolume, exec, $script/set-shader next

binde = , XF86MonBrightnessDown, exec, brightnessctl set 5%-
binde = , XF86MonBrightnessUp, exec, brightnessctl set +5%
binde = ALT, XF86MonBrightnessDown, exec, brightnessctl set 1%-
binde = ALT, XF86MonBrightnessUp, exec, brightnessctl set +1%
binde = SHIFT, XF86MonBrightnessDown, exec, brightnessctl set 1%
binde = SHIFT, XF86MonBrightnessUp, exec, brightnessctl set 100%

bindle = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bindle = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bindle = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bindle = ALT, XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -1%
bindle = ALT, XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +1%
bindle = SHIFT, XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ 0%
bindle = SHIFT, XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ 100%

bind = , XF86Search, exec, walker
