bind = $modifier SHIFT ALT, 0, exec, hyprctl keyword general:layout monocle
bind = $modifier SHIFT ALT, 1, exec, hyprctl keyword general:layout monocle && hyprctl keyword scrolling:column_width 1.00 && hyprctl keyword general:layout scrolling
bind = $modifier SHIFT ALT, 2, exec, hyprctl keyword general:layout monocle && hyprctl keyword scrolling:column_width 0.50 && hyprctl keyword general:layout scrolling
bind = $modifier SHIFT ALT, 3, exec, hyprctl keyword general:layout monocle && hyprctl keyword scrolling:column_width 0.33 && hyprctl keyword general:layout scrolling
bind = $modifier SHIFT ALT, 4, exec, hyprctl keyword general:layout dwindle
bind = $modifier SHIFT ALT, 5, exec, hyprctl keyword general:layout master
