bind = $modifier SHIFT ALT, 0, exec, $script/layout
bind = $modifier SHIFT ALT, 1, exec, $script/layout scrolling 100%
bind = $modifier SHIFT ALT, 2, exec, $script/layout scrolling
bind = $modifier SHIFT ALT, 3, exec, $script/layout scrolling 33%
bind = $modifier SHIFT ALT, 4, exec, $script/layout dwindle
bind = $modifier SHIFT ALT, 5, exec, $script/layout master
