bind = CTRL ALT, mouse:275, changegroupactive, f
bind = CTRL ALT, mouse:276, changegroupactive, b

bind = $modifier, mouse:275, layoutmsg, cycleprev
bind = $modifier, mouse:276, layoutmsg, cyclenext

bind = $modifier, mouse:275, movefocus, l
bind = $modifier, mouse:276, movefocus, r

bind = $modifier SHIFT, mouse:275, movewindow, l
bind = $modifier SHIFT, mouse:276, movewindow, r

bind = $modifier CTRL, mouse:275, swapwindow, l
bind = $modifier CTRL, mouse:276, swapwindow, r

bind = $modifier ALT, mouse:275, exec, hyprnome --previous --no-empty
bind = $modifier ALT, mouse:276, exec, hyprnome 
