bind = $modifier ALT, mouse:274, togglespecialworkspace

bindm = $modifier, mouse:272, movewindow
bindm = $modifier, mouse:273, resizewindow

bindn = $modifier CTRL ALT, mouse:272, killactive
bindn = $modifier CTRL ALT, mouse:273, forcekillactive


