bind = , $mouseClickMiddle, exec, 

bind = $modifier, $mouseScrollUp, layoutmsg, cycleprev
bind = $modifier, $mouseScrollDown, layoutmsg, cycleprev

bind = $modifier, $mouseScrollUp, movefocus, l
bind = $modifier, $mouseScrollDown, movefocus, r

bindm = $modifier, $mouseClickRight, resizewindow

bindm = $modifier, $mouseClickLeft, movewindow

bindr = $modifier $controlLeft $alternateLeft, $mouseClickLeft, killactive
bindr = $modifier $controlLeft $alternateLeft, $mouseClickRight, forcekillactive

bind = $modifier $alternateLeft, $mouseClickMiddle, togglespecialworkspace

bind = $modifier $alternateLeft, $mouseScrollUp, exec, hyprnome --previous --no-empty
bind = $modifier $alternateLeft, $mouseScrollDown, exec, hyprnome 

bind = $modifier $shiftLeft, $mouseScrollUp, movewindow, l
bind = $modifier $shiftLeft, $mouseScrollDown, movewindow, r

bind = $modifier $controlLeft, $mouseScrollUp, swapwindow, l
bind = $modifier $controlLeft, $mouseScrollDown, swapwindow, r

bind = $controlLeft $alternateLeft, $mouseScrollUp, changegroupactive, f
bind = $controlLeft $alternateLeft, $mouseScrollDown, changegroupactive, b


