bind = , mouse:274, exec, 

bind = $modifier, mouse_up, layoutmsg, cycleprev
bind = $modifier, mouse_down, layoutmsg, cycleprev

bind = $modifier, mouse_up, movefocus, l
bind = $modifier, mouse_down, movefocus, r

bindm = $modifier, mouse:273, resizewindow

bindm = $modifier, mouse:272, movewindow
bindr = $modifier, mouse:272, exec, $HOME/Documents/GitHub/hyprmousetrap/target/release/hyprmousetrap drag

bindr = $modifier CTRL ALT, mouse:272, killactive
bindr = $modifier CTRL ALT, mouse:273, forcekillactive

bind = $modifier ALT, mouse:274, togglespecialworkspace

bind = $modifier ALT, mouse_up, exec, hyprnome --previous --no-empty
bind = $modifier ALT, mouse_down, exec, hyprnome 

bind = $modifier CTRL, mouse_up, movewindow, l
bind = $modifier CTRL, mouse_down, movewindow, r

bind = $modifier SHIFT, mouse_up, swapwindow, l
bind = $modifier SHIFT, mouse_down, swapwindow, r

bind = CTRL ALT, mouse_up, changegroupactive, f
bind = CTRL ALT, mouse_down, changegroupactive, b


