bind = $modifier $controlLeft $alternateLeft, Left, exec, hyprnome --previous --move --no-empty
bind = $modifier $controlLeft $alternateLeft, Right, exec, hyprnome --move

bind = $modifier $controlLeft $alternateLeft, Home, movetoworkspace, e~0
bind = $modifier $controlLeft $alternateLeft, End, movetoworkspace, empty

bind = $modifier $controlLeft $alternateLeft, Up, movetoworkspace, special
bind = $modifier $controlLeft $alternateLeft, Down, movetoworkspace, +0

bind = $modifier $controlLeft $alternateLeft, Tab, movetoworkspace, special:stylus
bind = $modifier $controlLeft $alternateLeft, Grave, movetoworkspace, special:radio


