bind = CTRL ALT, Down, changegroupactive, f
bind = CTRL ALT, Up, changegroupactive, b

bind = CTRL ALT, End, movewindoworgroup, r
bind = CTRL ALT, Home, movewindoworgroup, l

bind = CTRL ALT, Page_Down, movewindoworgroup, d
bind = CTRL ALT, Page_Up, movewindoworgroup, u

bind = CTRL ALT, Return, togglegroup

bind = SHIFT CTRL ALT, Return, lockactivegroup, toggle
