bind = $modifier CTRL ALT, Left, exec, hyprnome --previous --move --no-empty
bind = $modifier CTRL ALT, Right, exec, hyprnome --move

bindo = $modifier CTRL ALT, Left, movetoworkspace, e~0
bindo = $modifier CTRL ALT, Right, movetoworkspace, empty

bind = $modifier CTRL ALT, Up, movetoworkspace, special
bind = $modifier CTRL ALT, Down, movetoworkspace, +0
