bind = $controlLeft $alternateLeft, Return, togglegroup

bind = $controlLeft $alternateLeft, Right, changegroupactive, f
bind = $controlLeft $alternateLeft, Left, changegroupactive, b

bind = $controlLeft $shiftLeft $alternateLeft, Right, movewindoworgroup, r
bind = $controlLeft $shiftLeft $alternateLeft, Left, movewindoworgroup, l
bind = $controlLeft $shiftLeft $alternateLeft, Up, movewindoworgroup, u
bind = $controlLeft $shiftLeft $alternateLeft, Down, movewindoworgroup, d

