bind = CTRL ALT, Return, togglegroup

bind = CTRL ALT, Right, changegroupactive, f
bind = CTRL ALT, Left, changegroupactive, b

bind = CTRL ALT, End, movewindoworgroup, r
bind = CTRL ALT, Home, movewindoworgroup, l
bind = CTRL ALT, Page_Down, movewindoworgroup, d
bind = CTRL ALT, Page_Up, movewindoworgroup, u

