bind = $modifier $shiftLeft $controlLeft $alternateLeft, Left, movetoworkspacesilent, -1
bind = $modifier $shiftLeft $controlLeft $alternateLeft, Right, movetoworkspacesilent, +1

bind = $modifier $shiftLeft $controlLeft $alternateLeft, Home, movetoworkspacesilent, e~0
bind = $modifier $shiftLeft $controlLeft $alternateLeft, End, movetoworkspacesilent, empty

bind = $modifier $shiftLeft $controlLeft $alternateLeft, Up, movetoworkspacesilent, special
bind = $modifier $shiftLeft $controlLeft $alternateLeft, Down, movetoworkspacesilent, +0

bind = $modifier $shiftLeft $controlLeft $alternateLeft, Tab, movetoworkspacesilent, special:stylus
bind = $modifier $shiftLeft $controlLeft $alternateLeft, Grave, movetoworkspacesilent, special:radio
