bind = $modifier SHIFT CTRL ALT, Left, movetoworkspacesilent, -1
bind = $modifier SHIFT CTRL ALT, Right, movetoworkspacesilent, +1

bind = $modifier SHIFT CTRL ALT, Home, movetoworkspacesilent, e~0
bind = $modifier SHIFT CTRL ALT, End, movetoworkspacesilent, empty

bind = $modifier SHIFT CTRL ALT, Up, movetoworkspacesilent, special
bind = $modifier SHIFT CTRL ALT, Down, movetoworkspacesilent, +0

bind = $modifier SHIFT CTRL ALT, Tab, movetoworkspacesilent, special:stylus
bind = $modifier SHIFT CTRL ALT, Grave, movetoworkspacesilent, special:radio
