bind = $modifier $controlLeft $alternateLeft, Left, exec, hyprnome --previous --move --no-empty
bind = $modifier $controlLeft $alternateLeft, Right, exec, hyprnome --move

bind = $modifier $controlLeft $alternateLeft, Home, exec, hyprctl dispatch movetoworkspace $(hyprctl workspaces -j | jq 'map(select(.windows > 1)) | sort_by(.id) | .[0].id')
bind = $modifier $controlLeft $alternateLeft, End, exec, hyprctl dispatch workspace $(comm -23 <(seq 1 10 | sort) <(hyprctl workspaces -j | jq '.[] | .id' | sort) | head -n 1)

bind = $modifier $controlLeft $alternateLeft, Up, movetoworkspace, special
bind = $modifier $controlLeft $alternateLeft, Down, movetoworkspace, +0

bind = $modifier $controlLeft $alternateLeft, Tab, movetoworkspace, special:stylus
bind = $modifier $controlLeft $alternateLeft, Grave, movetoworkspace, special:radio


