bind = $modifier $controlLeft $alternateLeft, W, exec, $script/wallpaper image
bind = $modifier $controlLeft $alternateLeft, E, exec, $script/wallpaper video
bind = $modifier $controlLeft $alternateLeft, Q, exec, $script/wallpaper off
