bind = $modifier $ShiftLeft $alternateLeft, W, exec, $script/wallpaper image
bind = $modifier $ShiftLeft $alternateLeft, E, exec, $script/wallpaper video
bind = $modifier $ShiftLeft $alternateLeft, Q, exec, $script/wallpaper off
