bindr = $modifier, F4, exec, waypaper
bindr = $modifier, F5, exec, gnome-calculator
bindr = $modifier, F6, exec, dialect

bindr = $modifier, F7, exec, gnome-characters
bindo = $modifier, F7, exec, $script/shimeji toggle

bindr = $modifier, F8, exec, $script/screenshot
bindr = $modifier, F9, exec, eyedropper
