bind = $modifier, F4, exec, waypaper
bind = $modifier, F5, exec, gnome-calculator
bind = $modifier, F6, exec, dialect

bind = $modifier, F7, exec, gnome-characters
bind = $modifier ALT, F7, exec, $script/shimeji toggle

bind = $modifier, F8, exec, $script/screenshot
bind = $modifier, F9, exec, eyedropper
