bind = $modifier CTRL, R, submap, resize
submap = resize
binde = , Right, resizeactive, 1 0
binde = , Left, resizeactive, -1 0
binde = , Up, resizeactive, 0 -1
binde = , Down, resizeactive, 0 1
binde = SHIFT, Right, resizeactive, 10 0
binde = SHIFT, Left, resizeactive, -10 0
binde = SHIFT, Up, resizeactive, 0 -10
binde = SHIFT, Down, resizeactive, 0 10    
bind = , Escape, submap, reset 
submap = reset
