bind = $modifier $controlLeft, R, submap, resize
submap = resize
binde = , Right, resizeactive, 1 0
binde = , Left, resizeactive, -1 0
binde = , Up, resizeactive, 0 -1
binde = , Down, resizeactive, 0 1
binde = $shiftLeft, Right, resizeactive, 10 0
binde = $shiftLeft, Left, resizeactive, -10 0
binde = $shiftLeft, Up, resizeactive, 0 -10
binde = $shiftLeft, Down, resizeactive, 0 10    
bind = , Escape, submap, reset 
submap = reset
