binde = $modifier, XF86AudioMute, exec, $script/set-shader off

binde = $modifier, XF86AudioLowerVolume, exec, $script/set-shader prev
binde = $modifier, XF86AudioRaiseVolume, exec, $script/set-shader next
