bind = $modifier ALT, Return, exec, hyprlock                                                                                                                                                                                                            
bind = , XF86PowerOff, exec, $script/shutdown
