bind = $modifier, $modifierLeft, exec, walker --close
bind = $modifier, $modifierLeft, exec, $script/submap-reset
bind = $modifier, $modifierLeft, submap, specialworkspace
submap = specialworkspace
bind = $modifier, $modifierLeft, togglespecialworkspace
bind = , Escape, workspace, +0
bind = $modifier, $modifierLeft, submap, reset
submap = reset

bind = $modifier, Grave, togglespecialworkspace, radio
bind = $modifier, Tab, togglespecialworkspace, stylus

bindr = $modifier ALT, ALT, workspace, +0

