bindr = $modifier, $modifierLeft, exec, $script/submap-reset
bindr = $modifier, $modifierLeft, exec, walker --close
bindr = $modifier, $modifierLeft, submap, specialworkspace

submap = specialworkspace
bindr = $modifier, $modifierLeft, togglespecialworkspace

bindr = , Grave, togglespecialworkspace, radio
bindr = , Tab, togglespecialworkspace, stylus

bindr = , Escape, workspace, +0

bindr = $modifier, $modifierLeft, submap, reset
submap = reset

bindr = $modifier $alternate, $alternateLeft, workspace, +0
