bindr = $modifier ALT, ALT_L, exec, $script/run-submap-reset-timer
bindr = $modifier ALT, ALT_L, submap, walker
submap = walker
bind = $modifier ALT, ALT_L, togglespecialworkspace, background
bind = $modifier ALT, ALT_L, submap, reset
submap = reset
