bind = $modifier $controlLeft, Down, swapwindow, d
bind = $modifier $controlLeft, Left,  swapwindow, l
bind = $modifier $controlLeft, Right, swapwindow, r
bind = $modifier $controlLeft, Up,  swapwindow, u
