bind = $modifier CTRL ALT, D, exec, $script/set-theme
bind = $modifier CTRL ALT, C, exec, $script/set-theme cartoon
bind = $modifier CTRL ALT, X, exec, $script/set-theme mono
bind = $modifier CTRL ALT, F, exec, $script/set-theme focus
bind = $modifier CTRL ALT, V, exec, $script/set-theme void
