bind = $modifier $shiftLeft $alternateLeft, D, exec, $script/theme
bind = $modifier $shiftLeft $alternateLeft, C, exec, $script/theme cartoon
bind = $modifier $shiftLeft $alternateLeft, X, exec, $script/theme mono
bind = $modifier $shiftLeft $alternateLeft, F, exec, $script/theme focus
bind = $modifier $shiftLeft $alternateLeft, V, exec, $script/theme void

