bind = CTRL ALT, D, exec, $script/set-theme
bind = CTRL ALT, C, exec, $script/set-theme cartoon
bind = CTRL ALT, X, exec, $script/set-theme mono
bind = CTRL ALT, F, exec, $script/set-theme focus
bind = CTRL ALT, V, exec, $script/set-theme void
