bindle = , $volumeMute, exec, pamixer --toggle-mute 

bindle = , $volumeDown, exec, pamixer --decrease 5
bindle = , $volumeUp, exec, pamixer --increase 5 --set-limit 100

bindle = $alternateLeft, $volumeDown, exec, pamixer --decrease 1
bindle = $alternateLeft, $volumeUp, exec, pamixer --increase 1 --set-limit 100

bindle = $controltLeft, $volumeDown, exec, pamixer --set-volume 0
bindle = $controlLeft, $volumeUp, exec, pamixer --set-volume 100

