bindle = , XF86AudioMute, exec, pamixer --toggle-mute 

bindle = , XF86AudioLowerVolume, exec, pamixer --decrease 5
bindle = , XF86AudioRaiseVolume, exec, pamixer --increase 5 --set-limit 100

bindle = ALT, XF86AudioLowerVolume, exec, pamixer --decrease 1
bindle = ALT, XF86AudioRaiseVolume, exec, pamixer --increase 1 --set-limit 100

bindle = SHIFT, XF86AudioLowerVolume, exec, pamixer --set-volume 0
bindle = SHIFT, XF86AudioRaiseVolume, exec, pamixer --set-volume 100

