bindle = , $volumeMute, exec, pamixer --toggle-mute 

bindle = , $volumeDown, exec, pamixer --decrease 5
bindle = , $volumeUp, exec, pamixer --increase 5 --set-limit 100

bindle = ALT, $volumeDown, exec, pamixer --decrease 1
bindle = ALT, $volumeUp, exec, pamixer --increase 1 --set-limit 100

bindle = CTRLtLeft, $volumeDown, exec, pamixer --set-volume 0
bindle = CTRL, $volumeUp, exec, pamixer --set-volume 100

