bind = , XF86Search, exec, walker

bindr = ALT, ALT_L, exec, $script/run-submap-reset-timer
bindr = ALT, ALT_L, submap, walker
submap = walker
bind = ALT, ALT_L, exec, walker
bind = ALT, ALT_L, submap, reset
submap = reset
