bind = , XF86Search, exec, walker

bindr = $alternate, $alternateLeft, exec, $script/submap-reset
bindr = $alternate, $alternateLeft, submap, walker

submap = walker
bind = $alternate, $alternateLeft, exec, walker
bind = $alternate, $alternateLeft, submap, reset
submap = reset

bind = $alternate, Tab, exec, walker --provider windows

