bind = , XF86Search, exec, walker

bindr = $modifier, $modifierLeft, exec, sleep 0.5; hyprctl dispatch submap reset
bindr = $modifier, $modifierLeft, submap, walker
submap = walker
bind = $modifier, $modifierLeft, exec, walker
bind = $modifier, $modifierLeft, submap, reset
submap = reset
