bind = CTRL ALT, mouse_up, changegroupactive, f
bind = CTRL ALT, mouse_down, changegroupactive, b

bind = $modifier, mouse_up, layoutmsg, cycleprev
bind = $modifier, mouse_down, layoutmsg, cyclenext

bind = $modifier, mouse_up, movefocus, l
bind = $modifier, mouse_down, movefocus, r

bind = $modifier SHIFT, mouse_up, movewindow, l
bind = $modifier SHIFT, mouse_down, movewindow, r

bind = $modifier CTRL, mouse_up, swapwindow, l
bind = $modifier CTRL, mouse_down, swapwindow, r

bind = $modifier ALT, mouse_up, exec, hyprnome --previous --no-empty
bind = $modifier ALT, mouse_down, exec, hyprnome 
