bind = $modifier, Return, fullscreen

bind = $modifier $controlLeft, Down, settiled
bind = $modifier $controlLeft, Up, setfloating
bind = $modifier $controlLeft, Up, resizeactive, exact 1200 800
bind = $modifier $controlLeft, Up, centerwindow
bind = $modifier $controlLeft, Return, pin
