bind = $modifier, Return, fullscreen

bind = $modifier $controlLeft, Down, settiled
bind = $modifier $controlLeft, Up, setfloating
bind = $modifier $controlLeft, Return, pin
bind = $modifier $controlLeft, Escape, centerwindow
