bind = $modifier ALT, Left, exec, hyprnome --previous --no-empty --keep-special
bind = $modifier ALT, Right, exec, hyprnome --keep-special

bind = $modifier ALT, Home, workspace, e~0
bind = $modifier ALT, End, workspace, empty

