bind = $modifier ALT, Left, exec, hyprnome --previous --no-empty
bind = $modifier ALT, Right, exec, hyprnome 

bindo = $modifier ALT, Left, workspace, e~0
bindo = $modifier ALT, Right, workspace, empty

