bind = $modifier $alternateLeft, Left, exec, hyprnome --previous --no-empty --keep-special
bind = $modifier $alternateLeft, Right, exec, hyprnome --keep-special

bind = $modifier $alternateLeft, Home, workspace, e~0
bind = $modifier $alternateLeft, End, workspace, empty

