bind = $modifier CTRL ALT, 0, exec, hyprctl reload
bind = $modifier CTRL ALT, 1, exec, hyprctl keyword monitor "eDP-1, 2880x1920@60, 0x0, 1"
bind = $modifier CTRL ALT, 2, exec, hyprctl keyword monitor "eDP-1, 2880x1920@60, 0x0, 2"
bind = $modifier CTRL ALT, 3, exec, hyprctl keyword monitor "eDP-1, 2880x1920@60, 0x0, 3"
