bind = $controlLeft $alternateLeft, 0, exec, hyprctl reload

bind = $controlLeft $alternateLeft, 1, exec, hyprctl keyword monitor "eDP-1, 2880x1920@60, 0x0, 1"
bind = $controlLeft $alternateLeft, 2, exec, hyprctl keyword monitor "eDP-1, 2880x1920@60, 0x0, 2"
bind = $controlLeft $alternateLeft, 3, exec, hyprctl keyword monitor "eDP-1, 2880x1920@60, 0x0, 3"
