hl.config({
	cursor = {
		default_monitor = "",
		enable_hyprcursor = true,
		hide_on_key_press = true,
		hide_on_tablet = true,
		hide_on_touch = true,
		hotspot_padding = 1,
		inactive_timeout = 0.0,
		invisible = false,
		min_refresh_rate = 60,
		no_break_fs_vrr = 1,
		no_hardware_cursors = 0,
		no_warps = true,
		persistent_warps = true,
		sync_gsettings_theme = true,
		use_cpu_buffer = 2,
		warp_back_after_non_mouse_input = false,
		warp_on_change_workspace = 0,
		warp_on_toggle_special = 0,
		zoom_detached_camera = true,
		zoom_disable_aa = false,
		zoom_factor = 1.0,
		zoom_rigid = false,
	},
})
