 gestures {
    workspace_swipe_cancel_ratio = 0.15

    gesture = 3, left, dispatcher, layoutmsg, cycleprev
    gesture = 3, right, dispatcher, layoutmsg, cyclenext

    gesture = 3, down, dispatcher, exec, pgrep walker || walker
    gesture = 3, up, dispatcher, exec, walker --close

    gesture = 4, horizontal, workspace
    gesture = 4, vertical, dispatcher, togglespecialworkspace, background
}
