 gestures {
    workspace_swipe_cancel_ratio = 0.15

    gesture = 4, horizontal, workspace
    gesture = 4, vertical, dispatcher, togglespecialworkspace, background

    gesture = 3, left, dispatcher, layoutmsg, cycleprev
    gesture = 3, right, dispatcher, layoutmsg, cyclenext
}
