input {
    accel_profile = adaptive
    float_switch_override_focus = 0
    follow_mouse = 1
    kb_layout = us,ru
    kb_options = grp:win_space_toggle, caps:hyper
    mouse_refocus = false
    scroll_factor = 2.0
    sensitivity = 0.36
    virtualkeyboard:share_states = 2

    touchpad {
        clickfinger_behavior = true
        disable_while_typing = true
        natural_scroll = true
    }
}

device {
    enabled = true
    name = hailuck-co.-ltd-usb-keyboard-touchpad
    disable_while_typing = true
    natural_scroll = true
}
