input {
    accel_profile = adaptive
    float_switch_override_focus = 1
    follow_mouse = 1
    kb_layout = us,ru
    kb_options = grp:caps_toggle
    mouse_refocus = true
    scroll_factor = 2.0
    sensitivity = 0.36

    touchpad {
        clickfinger_behavior = true
        disable_while_typing = true
        natural_scroll = true
        drag_lock = false
    }
}

device {
    enabled = true
    name = hailuck-co.-ltd-usb-keyboard-touchpad
    disable_while_typing = true
    natural_scroll = true
}
