input {
    accel_profile = adaptive
    float_switch_override_focus = true
    follow_mouse = true
    kb_layout = us,ru
    kb_options = grp:caps_toggle
    mouse_refocus = true
    scroll_button = 274
    scroll_button_lock = true
    scroll_factor = 1.0
    scroll_method = on_button_down
    sensitivity = 0

    touchpad {
        clickfinger_behavior = true
        disable_while_typing = true
        natural_scroll = true
        drag_lock = false
    }
}

device {
    enabled = true
    name = hailuck-co.-ltd-usb-keyboard-touchpad
}
