hl.curve("vapor",        { type = "spring", mass = 1.00, stiffness = 4,   dampening = 2 })
hl.curve("bubble",       { type = "spring", mass = 1.00, stiffness = 16,  dampening = 4 })
hl.curve("fluff",        { type = "spring", mass = 1.00, stiffness = 49,  dampening = 7 })
hl.curve("ball",         { type = "spring", mass = 1.00, stiffness = 100, dampening = 10 })
hl.curve("leaf",         { type = "spring", mass = 1.00, stiffness = 196, dampening = 14 })
hl.curve("rubber",       { type = "spring", mass = 1.00, stiffness = 361, dampening = 19 })

hl.curve("feather",      { type = "spring", mass = 1.05, stiffness = 25,  dampening = 10 })
hl.curve("silk",         { type = "spring", mass = 1.10, stiffness = 81,  dampening = 18 })
hl.curve("card",         { type = "spring", mass = 1.15, stiffness = 169, dampening = 26 })
hl.curve("coin",         { type = "spring", mass = 1.20, stiffness = 289, dampening = 34 })
hl.curve("puck",         { type = "spring", mass = 1.25, stiffness = 441, dampening = 42 })
hl.curve("magnet",       { type = "spring", mass = 1.30, stiffness = 676, dampening = 52 })
hl.curve("whip",         { type = "spring", mass = 1.40, stiffness = 961, dampening = 62 })

hl.curve("book",         { type = "spring", mass = 1.50, stiffness = 144, dampening = 48 })
hl.curve("timber",       { type = "spring", mass = 1.70, stiffness = 256, dampening = 64 })
hl.curve("ingot",        { type = "spring", mass = 1.95, stiffness = 400, dampening = 80 })
hl.curve("marble",       { type = "spring", mass = 2.20, stiffness = 576, dampening = 96 })
hl.curve("anchor",       { type = "spring", mass = 2.50, stiffness = 784, dampening = 112 })
hl.curve("anvil",        { type = "spring", mass = 2.80, stiffness = 900, dampening = 120 })
hl.curve("glacier",      { type = "spring", mass = 3.00, stiffness = 961, dampening = 124 })

