hl.config({
	group = {
		disable_when_only = false,
		enabled = true,
		font_family = "Ubuntu Sans Mono",
		font_size = 10,
		font_weight_active = "normal",
		font_weight_inactive = "normal",
		gaps_in = 2,
		gaps_out = 2,
		gradient_round_only_edges = true,
		gradient_rounding = 2,
		gradient_rounding_power = 2.0,
		gradients = false,
		height = 14,
		indicator_gap = -6,
		indicator_height = 3,
		keep_upper_gap = true,
		middle_click_close = true,
		priority = 3,
		render_titles = false,
		round_only_edges = true,
		rounding = 0,
		rounding_power = 2.0,
		scrolling = true,
		stacked = false,
		text_color = 0xf7f7f7f7,
		text_color_inactive = nil,
		text_color_locked_active = nil,
		text_color_locked_inactive = nil,
		text_offset = 0,
		text_padding = 0,
		groupbar = {},
	},
})

require("hyprland.core.config.group.groupbar.col")
