background #171717
foreground #929292

selection_background #7D97F1
selection_foreground #F7F7F7

url_color #7D97F1

cursor #EBEBEB
cursor_text_color #171717

active_border_color #272727
inactive_border_color #272727
bell_border_color #272727
visual_bell_color #272727

active_tab_background #171717
active_tab_foreground #EBEBEB
inactive_tab_background #171717
inactive_tab_foreground #4C4C4C
tab_bar_background #171717
tab_bar_margin_color #171717

color0 #171717
color1 #882015
color2 #315717
color3 #5B4A16
color4 #2628C6
color5 #5E21A0
color6 #1A574D
color7 #9D9D9D
color8 #4C4C4C
color9 #F26F5C
color10 #6BB338
color11 #BA9937
color12 #7D97F1
color13 #AD83F1
color14 #3EB39F

color15 #F7F7F7

mark1_foreground #E1C77F
mark1_background #0F152C

mark2_foreground #60C8B5
mark2_background #0F152C

mark3_foreground #D299EB
mark3_background #0F152C
