background #171717
foreground #9D9D9D

selection_background #6A9DF1
selection_foreground #F7F7F7

url_color #6A9DF1

cursor #F7F7F7
cursor_text_color #171717

active_border_color #272727
inactive_border_color #272727
bell_border_color #272727
visual_bell_color #272727

active_tab_background #171717
active_tab_foreground #F7F7F7
inactive_tab_background #171717
inactive_tab_foreground #4C4C4C
tab_bar_background #171717
tab_bar_margin_color #171717

color0  #171717
color1  #D32111
color2  #168A41
color3  #996812
color4  #435CF8
color5  #9121F8
color6  #168190
color7  #9D9D9D
color8  #4C4C4C
color9  #F27050
color10 #3EB774
color11 #C59437
color12 #8595F1
color13 #B67EF1
color14 #3DADC5
color15 #F7F7F7

mark1_foreground #F7F7F8
mark1_background #142746

mark2_foreground #F6F8F7
mark2_background #1A2D15

mark3_foreground #F8F7F6
mark3_background #41191B

