map ctrl+c                          copy_or_interrupt
map ctrl+v                          paste_from_clipboard

map kitty_mod+enter                 launch --cwd=current
map kitty_mod+t                     new_tab_with_cwd

map ctrl+tab                        next_window
map shift+ctrl+tab                  previous_window

map kitty_mod+home                  move_window_backward
map kitty_mod+end                   move_window_forward
