$special = special:special
$radio = special:radio
$stylus = special:stylus

corner = 2
edge = 2

zone = , , , bottom left, , , exec, hyprnome --previous --no-empty --keep-special 
zone = , , , bottom right, , , exec, hyprnome --keep-special

zone = , , , bottom left, SUPER, , exec, hyprctl dispatch workspace $(hyprctl workspaces -j | jq 'map(select(.windows > 0)) | sort_by(.id) | .[0].id')
zone = , , , bottom right, SUPER, , exec, hyprctl dispatch workspace $(comm -23 <(seq 1 10 | sort) <(hyprctl workspaces -j | jq '.[] | .id' | sort) | head -n 1)

zone = , , , top right, , 2000, exec, hyprlock

zone = , , , top left, , 100, exec, walker
zone = , , $special, top left, , 100, exec, walker

zone = , , , top, , 2000, exec, killall waybar || waybar

zone = , , , bottom, , 500, exec, walker --close
zone = , , , bottom, , 1000, togglespecialworkspace

zone = , , $special, bottom, , 1000, workspace, +0
zone = , , $radio, bottom, , 1000, workspace, +0
zone = , , $stylus, bottom, , 1000, workspace, +0
