$special = special:special
$radio = special:radio
$stylus = special:stylus

corner = 2
edge = 2

zone = , , bottom left, , exec, hyprnome --previous --no-empty --keep-special 
zone = , , bottom left, 1000, workspace, e~0

zone = , , bottom right, , exec, hyprnome --keep-special
zone = , , bottom right, 1000, workspace, empty

zone = , , top right, 2000, exec, hyprlock

zone = , , top left, 100, exec, walker
zone = , $special, top left, 100, exec, walker

zone = , , bottom, 1000, togglespecialworkspace
zone = , , bottom, 1000, exec, walker --close

zone = , $special, bottom, 500, workspace, +0
zone = , $radio, bottom, 500, workspace, +0
zone = , $stylus, bottom, 500, workspace, +0

