accent = 0xf76f9ef6
accent_secondary = 0xf7a6c0f2
alternate_base = 0xf7202020
background = 0xf7202020
base = 0xf7292929
bright_text = 0xf7f8f8f8

font_family = Ubuntu Sans Mono
font_family_monospacce = Ubuntu Sans Mono
font_size = 11

h1_size = 19
h2_size = 15
h3_size = 13

rounding_large = 16
rounding_small = 8

small_font_sile = 9

text = 0xf7bfbfbf
