general {
    after_sleep_cmd = hyprctl dispatch dpms on
    before_sleep_cmd = hyprlock
    lock_cmd = pidof hyprlock || hyprlock
}

listener {
    on-timeout = $HOME/.config/hypr/script/run-unimatrix
    timeout = 60
}

listener {
    on-resume = brightnessctl --restore
    on-timeout = brightnessctl --save; brightnessctl set 10%
    timeout = 120
}

listener {
    on-resume = brightnessctl --restore
    on-timeout = brightnessctl brightnessctl set 1%
    timeout = 180
}

listener {
    on-resume = pkill -f "/usr/bin/unimatrix" 
    on-timeout = hyprlock
    timeout = 360
}

listener {
    on-resume = hyprctl dispatch dpms on
    on-timeout = hyprctl dispatch dpms off
    timeout = 720
}

listener {
    on-timeout = systemctl suspend
    timeout = 1440
}

listener {
    on-timeout = systemctl poweroff
    timeout = 2880
}


