profile {
    name = day
    time = 07:00
    temperature = 6500
}

profile {
    name = evening
    time = 18:00 
    temperature = 4000
}

profile {
    name = night
    time = 21:00
    temperature = 2700
}

profile {
    name = deep
    time = 23ыы:00
    temperature = 2000
}
