corner = 64
edge = 8

zone = , , top left, , exec, hyprnome --previous --no-empty --keep-special 
zone = , , top right, , exec, hyprnome --keep-special

zone = , , bottom right, , exec, walker

zone = , , bottom left, , togglespecialworkspace
