general {
    after_sleep_cmd = hyprctl dispatch dpms on
    before_sleep_cmd = pidof hyprlock || hyprlock
    lock_cmd = pidof hyprlock || hyprlock
}

listener {
    timeout = 120
    on-timeout = brightnessctl --save && brightnessctl set 10%
    on-resume = brightnessctl --restore
}

listener {
    timeout = 180
    on-timeout = brightnessctl set 1%
    on-resume = brightnessctl --restore
}

listener {
    timeout = 360
    on-timeout = pidof hyprlock || hyprlock
}

listener {
    timeout = 720
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 1440
    on-timeout = systemctl suspend
}

