general {
    hide_cursor = true
    no_fade_in = false
    no_fade_out = false
}

background {
    blur_passes = 4
    blur_size = 8
    color = 0x00000000
    path = screenshot
}

shape {
    border_size = 0
    color = 0x1eededed
    halign = center
    position = 0, 50
    rounding = 0
    size = 1, 896
    valign = top
}

label {
    color = 0xffededed 
    font_family = Ubuntu Sans Mono
    font_size = 14
    halign = center
    position = 0, 64
    text = cmd[update:60000] echo "$(date +"%H:%M")"
    valign = center
}

label {
    color = 0xffededed 
    font_family = Ubuntu Sans Mono
    font_size = 14
    halign = center
    position = 0, -64
    text = cmd[] echo "$(date +"%d %b %Y")"
    valign = center
}

label {
    color = 0xffededed 
    font_family = Ubuntu Sans Mono
    font_size = 14
    halign = center
    position = 0, -96
    text = cmd[] echo "$(date +"%a")"
    valign = center
}

input-field {
    check_color = 0x00000000
    dots_center = true
    dots_size = 0.16
    dots_spacing = 0.32
    fade_on_empty = false
    fail_color = 0xffe1756d
    fail_text = 
    fail_transition = 100
    font_color = 0xffededed
    font_family = Ubuntu Sans Mono
    font_size = 14
    halign = center
    hide_input = false
    inner_color = 0x1aededed
    outer_color = 0x00000000
    outline_thickness = 0
    placeholder_text = 
    size = 256, 64
    valign = center
}

