$script = $HOME/.config/hypr/script

spin = , normal, exec, $script/layout scrolling
spin = , bottom-up, exec, $script/layout scrolling
spin = , left-up, exec, $script/layout scrolling 100%
spin = , right-up, exec, $script/layout scrolling 100%
