accent = 0xff6d8af4
accent_secondary = 0xff9db1eb
alternate_base = 0xff1f1f1f
background = 0xff1f1f1f
base = 0xff272727
bright_text = 0xffefefef

font_family = Ubuntu Sans Mono
font_family_monospacce = Ubuntu Sans Mono
font_size = 11

h1_size = 19
h2_size = 15
h3_size = 13

rounding_large = 16
rounding_small = 8

small_font_sile = 9

text = 0xffbebebe
