accent = 0xff6891ec
accent_secondary = 0xffa6c0f7
alternate_base = 0xff212121
background = 0xff131313
base = 0xff1a1a1a
bright_text = 0xffefefef

font_family = Ubuntu Sans Mono
font_family_monospacce = Ubuntu Sans Mono
font_size = 11

h1_size = 19
h2_size = 15
h3_size = 13

rounding_large = 16
rounding_small = 8

small_font_sile = 9

text = 0xffc0c0c0
