hl.animation({ leaf = "fade", enabled = true, speed = 5, bezier = "easeOutQuad" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 2, bezier = "easeOutQuad" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 5, bezier = "easeInSine" })
hl.animation({ leaf = "fadeSwitch", enabled = true, speed = 5, bezier = "easeOutQuad" })
hl.animation({ leaf = "fadeShadow", enabled = true, speed = 5, bezier = "easeOutQuad" })
hl.animation({ leaf = "fadeDim", enabled = true, speed = 1, bezier = "easeOutSine" })
hl.animation({ leaf = "fadeLayers", enabled = true, speed = 3, bezier = "easeOutQuad" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 3, bezier = "easeOutQuad" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 5, bezier = "easeInSine" })
hl.animation({ leaf = "fadePopups", enabled = true, speed = 3, bezier = "easeOutQuad" })
hl.animation({ leaf = "fadePopupsIn", enabled = true, speed = 3, bezier = "easeOutQuad" })
hl.animation({ leaf = "fadePopupsOut", enabled = true, speed = 1, bezier = "easeInSine" })
hl.animation({ leaf = "fadeDpms", enabled = true, speed = 5, bezier = "easeOutQuad" })

