general {
    gaps_workspaces = 32
    persistent_workspaces = false

    gaps_in = 4
    gaps_out = 24
    
    border_size = 1

    col.active_border = 0x94ffffff
    col.inactive_border = 0x49ffffff

    resize_on_border = false 
    allow_tearing = false
    
    layout = scrolling

    snap {
        enabled = true
        window_gap = 16
        monitor_gap = 16
    }
}

