group {
    col.active_border = 0x6bffffff
    col.inactive_border = 0x49ffffff

    col.border_locked_active = 0x6bffffff
    col.border_locked_inactive = 0x49ffffff

    groupbar {

        col.active = 0xedffffff
        col.inactive = 0x49ffffff

        col.locked_active = 0xedffffff
        col.locked_inactive = 0x49ffffff

        indicator_gap = -6
        indicator_height = 3
        rounding = 0

        render_titles = false
        round_only_edges = true
    }
}
