return function(colors)
	return {
		Boolean = { fg = colors.wine[12], bold = true },
		Character = { fg = colors.coral[16], bold = true },
		Comment = { fg = colors.gray[8], italic = true },
		Conditional = { fg = colors.rose[18], bold = true },
		Constant = { fg = colors.azure[12] },
		Define = { fg = colors.cobalt[18], bold = true },
		Delimiter = { fg = colors.gray[18] },
		Exception = { fg = colors.red[18], bold = true },
		Float = { fg = colors.yellow[12] },
		Function = { fg = colors.blue[16] },
		Identifier = { fg = colors.magenta[12] },
		Include = { fg = colors.raspberry[18], bold = true },
		Keyword = { fg = colors.gray[24], bold = true },
		Macro = { fg = colors.indigo[12] },
		Number = { fg = colors.orange[12] },
		Operator = { fg = colors.rose[18], bold = true },
		PreCondit = { fg = colors.rose[18], bold = true },
		PreProc = { fg = colors.cobalt[18], bold = true },
		PunctuationBracket = { fg = colors.cyan[8] },
		Repeat = { fg = colors.orange[18], bold = true },
		Special = { fg = colors.rose[18] },
		SpecialChar = { fg = colors.orange[12], bold = true },
		SpecialComment = { fg = colors.gray[8], italic = true },
		StorageClass = { fg = colors.gray[24], bold = true },
		String = { fg = colors.red[8] },
		Structure = { fg = colors.mint[12] },
		Tag = { fg = colors.gray[24], bold = true },
		Todo = { fg = colors.gray[8], italic = true },
		Type = { fg = colors.orchid[12] },
		Typedef = { fg = colors.cobalt[18], bold = true },
	}
end
