return function(colors)
	return {
		Boolean = { fg = colors.Wine12, bold = true },
		Character = { fg = colors.Coral16, bold = true },
		Comment = { fg = colors.Gray8, italic = true },
		Conditional = { fg = colors.Rose18, bold = true },
		Constant = { fg = colors.Azure12 },
		Define = { fg = colors.Cobalt18, bold = true },
		Delimiter = { fg = colors.Gray18 },
		Exception = { fg = colors.Red18, bold = true },
		Float = { fg = colors.Yellow12 },
		Function = { fg = colors.Blue16 },
		Identifier = { fg = colors.Magenta12 },
		Include = { fg = colors.Raspberry18, bold = true },
		Keyword = { fg = colors.Gray24, bold = true },
		Macro = { fg = colors.Indigo12 },
		Number = { fg = colors.Orange12 },
		Operator = { fg = colors.Rose18, bold = true },
		PreCondit = { fg = colors.Rose18, bold = true },
		PreProc = { fg = colors.Cobalt18, bold = true },
		PunctuationBracket = { fg = colors.Cyan8 },
		Repeat = { fg = colors.Orange18, bold = true },
		Special = { fg = colors.Rose18 },
		SpecialChar = { fg = colors.Orange12, bold = true },
		SpecialComment = { fg = colors.Gray8, italic = true },
		StorageClass = { fg = colors.Gray24, bold = true },
		String = { fg = colors.Red8 },
		Structure = { fg = colors.Mint12 },
		Tag = { fg = colors.Gray24, bold = true },
		Todo = { fg = colors.Gray8, italic = true },
		Type = { fg = colors.Orchid12 },
		Typedef = { fg = colors.Cobalt18, bold = true },
	}
end
