return function(colors)
	return {
		DiagnosticDeprecated = { strikethrough = true, fg = colors.gray[20] },
		DiagnosticError = { fg = colors.red[20] },
		DiagnosticHint = { fg = colors.indigo[20] },
		DiagnosticInfo = { fg = colors.blue[20] },
		DiagnosticOk = { fg = colors.green[20] },
		DiagnosticSignError = { fg = colors.red[20] },
		DiagnosticSignHint = { fg = colors.indigo[20] },
		DiagnosticSignInfo = { fg = colors.blue[20] },
		DiagnosticSignWarn = { fg = colors.orange[20] },
		DiagnosticUnderlineError = { undercurl = true, sp = colors.red[20] },
		DiagnosticUnderlineHint = { undercurl = true, sp = colors.indigo[20] },
		DiagnosticUnderlineInfo = { undercurl = true, sp = colors.blue[20] },
		DiagnosticUnderlineWarn = { undercurl = true, sp = colors.orange[20] },
		DiagnosticUnnecessary = { fg = colors.gray[20] },
		DiagnosticVirtualTextError = { fg = colors.red[20] },
		DiagnosticVirtualTextHint = { fg = colors.indigo[20] },
		DiagnosticVirtualTextInfo = { fg = colors.blue[20] },
		DiagnosticVirtualTextWarn = { fg = colors.orange[20] },
		DiagnosticWarn = { fg = colors.orange[20] },
		Error = { fg = colors.red[20] },
		ErrorMsg = { fg = colors.red[20] },
		Hint = { fg = colors.indigo[20] },
		Info = { fg = colors.blue[20] },
		MoreMsg = { fg = colors.gray[20] },
		Question = { fg = colors.indigo[20] },
		Warning = { fg = colors.orange[20] },
		WarningMsg = { fg = colors.orange[20] },
		healthError = { fg = colors.red[20] },
		healthSuccess = { fg = colors.green[20] },
		healthWarning = { fg = colors.orange[20] },
	}
end
