return function(colors)
	return {
		DiagnosticDeprecated = { strikethrough = true, fg = colors.Gray20 },
		DiagnosticError = { fg = colors.Red20 },
		DiagnosticHint = { fg = colors.Indigo20 },
		DiagnosticInfo = { fg = colors.Blue20 },
		DiagnosticOk = { fg = colors.Green20 },
		DiagnosticSignError = { fg = colors.Red20 },
		DiagnosticSignHint = { fg = colors.Indigo20 },
		DiagnosticSignInfo = { fg = colors.Blue20 },
		DiagnosticSignWarn = { fg = colors.Orange20 },
		DiagnosticUnderlineError = { undercurl = true, sp = colors.Red20 },
		DiagnosticUnderlineHint = { undercurl = true, sp = colors.Indigo20 },
		DiagnosticUnderlineInfo = { undercurl = true, sp = colors.Blue20 },
		DiagnosticUnderlineWarn = { undercurl = true, sp = colors.Orange20 },
		DiagnosticUnnecessary = { fg = colors.Gray20 },
		DiagnosticVirtualTextError = { fg = colors.Red20 },
		DiagnosticVirtualTextHint = { fg = colors.Indigo20 },
		DiagnosticVirtualTextInfo = { fg = colors.Blue20 },
		DiagnosticVirtualTextWarn = { fg = colors.Orange20 },
		DiagnosticWarn = { fg = colors.Orange20 },
		Error = { fg = colors.Red20 },
		ErrorMsg = { fg = colors.Red20 },
		Hint = { fg = colors.Indigo20 },
		Info = { fg = colors.Blue20 },
		MoreMsg = { fg = colors.Gray20 },
		Question = { fg = colors.Indigo20 },
		Warning = { fg = colors.Orange20 },
		WarningMsg = { fg = colors.Orange20 },
		healthError = { fg = colors.Red20 },
		healthSuccess = { fg = colors.Green20 },
		healthWarning = { fg = colors.Orange20 },
	}
end
