return function(colors)
	return {
		Bold = { bold = true },
		Conceal = { fg = colors.gray[6] },
		CurSearch = { fg = colors.gray[0], bg = colors.honey[8], bold = true },
		Cursor = { fg = colors.gray[0], bg = colors.gray[24] },
		CursorLine = { bg = colors.gray[2] },
		CursorLineNr = { fg = colors.gray[24], bg = colors.gray[2], bold = true },
		Directory = { fg = colors.blue[16] },
		EndOfBuffer = { fg = colors.gray[4] },
		FloatBorder = { fg = colors.gray[2], bg = colors.gray[1] },
		FloatTitle = { fg = colors.gray[24], bg = colors.gray[1], bold = true },
		FoldColumn = { fg = colors.blue[16] },
		Folded = { fg = colors.blue[16] },
		IncSearch = { fg = colors.gray[0], bg = colors.honey[8] },
		Italic = { italic = true },
		Label = { fg = colors.gray[16] },
		LineNr = { fg = colors.gray[6] },
		MatchParen = { fg = colors.honey[18], bold = true },
		ModeMsg = { fg = colors.Green20 },
		NonText = { fg = colors.gray[4] },
		Normal = { fg = colors.gray[16] },
		NormalFloat = { fg = colors.gray[16], bg = colors.gray[1] },
		NvimTreeFolderName = { fg = colors.blue[16], bold = true },
		NvimTreeNormal = { fg = colors.gray[16], bg = colors.gray[1] },
		NvimTreeOpenedFolderName = { fg = colors.blue[20], bold = true },
		NvimTreeWinSeparator = { fg = colors.gray[1], bg = colors.gray[1] },
		Pmenu = { fg = colors.gray[16], bg = colors.gray[1] },
		PmenuSbar = { bg = colors.gray[4] },
		PmenuSel = { fg = colors.gray[0], bg = colors.blue[16], bold = true },
		PmenuThumb = { bg = colors.gray[8] },
		Search = { fg = colors.honey[18], bg = colors.honey[8] },
		SignColumn = { bg = colors.gray[1] },
		SpecialKey = { fg = colors.gray[24] },
		SpellBad = { undercurl = true, sp = colors.red[20] },
		SpellCap = { undercurl = true, sp = colors.orange[20] },
		StatusLine = { fg = colors.gray[8] },
		StatusLineNC = { fg = colors.gray[8], bg = colors.gray[1] },
		TermCursor = { reverse = true },
		Title = { fg = colors.gray[24] },
		Underlined = { underline = true },
		Visual = { fg = colors.blue[24], bg = colors.blue[16] },
		WildMenu = { fg = colors.gray[0], bg = colors.blue[16] },
		WinSeparator = { fg = colors.gray[1] },
	}
end
