return function(colors)
	return {
		Bold = { bold = true },
		Conceal = { fg = colors.Gray6 },
		CurSearch = { fg = colors.Gray0, bg = colors.Yellow8, bold = true },
		Cursor = { fg = colors.Gray0, bg = colors.Gray24 },
		CursorLine = { bg = colors.Gray2 },
		CursorLineNr = { fg = colors.Gray24, bg = colors.Gray2, bold = true },
		Directory = { fg = colors.Indigo16 },
		EndOfBuffer = { fg = colors.Gray4 },
		FloatBorder = { fg = colors.Gray3, bg = colors.Gray2 },
		FloatTitle = { fg = colors.Gray24, bg = colors.Gray2, bold = true },
		FoldColumn = { fg = colors.Indigo16 },
		Folded = { fg = colors.Indigo16 },
		IncSearch = { fg = colors.Gray0, bg = colors.Yellow8 },
		Italic = { italic = true },
		Label = { fg = colors.Gray16 },
		LineNr = { fg = colors.Gray6 },
		MatchParen = { fg = colors.Yellow18, bold = true },
		ModeMsg = { fg = colors.Green20 },
		NonText = { fg = colors.Gray4 },
		Normal = { fg = colors.Gray16 },
		NormalFloat = { fg = colors.Gray16, bg = colors.Gray2 },
		NvimTreeFolderName = { fg = colors.Indigo16, bold = true },
		NvimTreeNormal = { fg = colors.Gray16, bg = colors.Gray1 },
		NvimTreeOpenedFolderName = { fg = colors.Indigo20, bold = true },
		NvimTreeWinSeparator = { fg = colors.Gray2, bg = colors.Gray1 },
		Pmenu = { fg = colors.Gray16, bg = colors.Gray2 },
		PmenuSbar = { bg = colors.Gray4 },
		PmenuSel = { fg = colors.Gray0, bg = colors.Indigo16, bold = true },
		PmenuThumb = { bg = colors.Gray8 },
		Search = { fg = colors.Yellow18, bg = colors.Yellow8 },
		SignColumn = { bg = colors.Gray1 },
		SpecialKey = { fg = colors.Gray24 },
		SpellBad = { undercurl = true, sp = colors.Red20 },
		SpellCap = { undercurl = true, sp = colors.Orange20 },
		StatusLine = { fg = colors.Gray8 },
		StatusLineNC = { fg = colors.Gray8, bg = colors.Gray2 },
		TermCursor = { reverse = true },
		Title = { fg = colors.Gray24 },
		Underlined = { underline = true },
		Visual = { fg = colors.Indigo24, bg = colors.Indigo16 },
		WildMenu = { fg = colors.Gray0, bg = colors.Indigo16 },
		WinSeparator = { fg = colors.Gray2 },
	}
end
