return function(colors)
	return {
		NvimTreeCursorColumn = { bg = colors.gray[2] },
		NvimTreeCursorLine = { bg = colors.gray[2] },
		NvimTreeDiagnosticError = { fg = colors.red[12] },
		NvimTreeDiagnosticHint = { fg = colors.gray[12] },
		NvimTreeDiagnosticInformation = { fg = colors.blue[12] },
		NvimTreeDiagnosticWarning = { fg = colors.orange[12] },
		NvimTreeEmptyFolderName = { fg = colors.blue[16] },
		NvimTreeEndOfBuffer = { fg = colors.gray[16] },
		NvimTreeExecFile = { fg = colors.green[16] },
		NvimTreeFileIcon = { fg = colors.gray[16] },
		NvimTreeFileSign = { fg = colors.gray[16] },
		NvimTreeFolderIcon = { fg = colors.blue[16], bold = true },
		NvimTreeFolderName = { fg = colors.blue[16], bold = true },
		NvimTreeFolderSign = { fg = colors.blue[16], bold = true },
		NvimTreeGitDeleted = { fg = colors.red[8] },
		NvimTreeGitDirty = { fg = colors.orange[16] },
		NvimTreeGitIgnored = { fg = colors.gray[8] },
		NvimTreeGitMerge = { fg = colors.red[16] },
		NvimTreeGitNew = { fg = colors.orchid[16] },
		NvimTreeGitRenamed = { fg = colors.honey[8] },
		NvimTreeGitStaged = { fg = colors.green[16] },
		NvimTreeImageFile = { fg = colors.rose[16] },
		NvimTreeIndent = { fg = colors.gray[4] },
		NvimTreeLiveFilterBackground = { bg = colors.gray[1] },
		NvimTreeLiveFilterPrefix = { fg = colors.gray[16] },
		NvimTreeLiveFilterValue = { fg = colors.gray[16] },
		NvimTreeMarkdownFile = { fg = colors.gray[16] },
		NvimTreeNormal = { fg = colors.gray[16] },
		NvimTreeOpenedFile = { fg = colors.gray[24] },
		NvimTreeOpenedFileIcon = { fg = colors.gray[24] },
		NvimTreeOpenedFolderName = { fg = colors.blue[16], bold = true },
		NvimTreeRootFolder = { fg = colors.blue[16], bold = true },
		NvimTreeSpecialFile = { fg = colors.gray[16] },
		NvimTreeStatusLine = { fg = colors.gray[16], bg = colors.gray[2] },
		NvimTreeStatusLineNC = { fg = colors.gray[16], bg = colors.gray[2] },
		NvimTreeSymlink = { fg = colors.cyan[16] },
		NvimTreeVertSplit = { fg = colors.gray[4] },
		NvimTreeWinSeparator = { fg = colors.gray[4] },
		NvimTreeWindowPicker = { fg = colors.gray[16], bg = colors.gray[2] },
	}
end
