return function(colors)
	return {
		NvimTreeNormal = { fg = colors.Gray12 },
		NvimTreeIndent = { fg = colors.Gray04 },
		NvimTreeSymlink = { fg = colors.Cyan16 },
		NvimTreeFolderName = { fg = colors.Blue16, bold = true },
		NvimTreeRootFolder = { fg = colors.Blue16, bold = true },
		NvimTreeFolderIcon = { fg = colors.Blue16, bold = true },
		NvimTreeFileIcon = { fg = colors.Gray12 },
		NvimTreeExecFile = { fg = colors.Green16 },
		NvimTreeSpecialFile = { fg = colors.Magenta16 },
		NvimTreeImageFile = { fg = colors.Magenta16 },
		NvimTreeMarkdownFile = { fg = colors.Blue16 },
		NvimTreeOpenedFolderName = { fg = colors.Blue16, bold = true },
		NvimTreeEmptyFolderName = { fg = colors.Gray12 },
		NvimTreeFolderSign = { fg = colors.Blue16 },
		NvimTreeFileSign = { fg = colors.Gray12 },
		NvimTreeWindowPicker = { fg = colors.Gray12, bg = colors.Gray0 },
		NvimTreeLiveFilterPrefix = { fg = colors.Yellow16 },
		NvimTreeLiveFilterValue = { fg = colors.Gray12 },
		NvimTreeLiveFilterBackground = { bg = colors.Gray1 },
		NvimTreeCursorLine = { bg = colors.Gray2 },
		NvimTreeCursorColumn = { bg = colors.Gray2 },
		NvimTreeVertSplit = { fg = colors.Gray04 },
		NvimTreeEndOfBuffer = { fg = colors.Gray12 },
		NvimTreeStatusLine = { fg = colors.Gray12, bg = colors.Gray0 },
		NvimTreeStatusLineNC = { fg = colors.Gray12, bg = colors.Gray0 },
		NvimTreeWinSeparator = { fg = colors.Gray04 },
		NvimTreeDiagnosticError = { fg = colors.Red16 },
		NvimTreeDiagnosticWarning = { fg = colors.Yellow16 },
		NvimTreeDiagnosticInformation = { fg = colors.Blue16 },
		NvimTreeDiagnosticHint = { fg = colors.Gray16 },
		NvimTreeGitDirty = { fg = colors.Yellow16 },
		NvimTreeGitStaged = { fg = colors.Green16 },
		NvimTreeGitMerge = { fg = colors.Amethyst16 },
		NvimTreeGitRenamed = { fg = colors.Purple12 },
		NvimTreeGitNew = { fg = colors.Green12 },
		NvimTreeGitDeleted = { fg = colors.Red12 },
		NvimTreeGitIgnored = { fg = colors.Gray08 },
	}
end
