return function(colors)
	return {
		NvimTreeCursorColumn = { bg = colors.Gray2 },
		NvimTreeCursorLine = { bg = colors.Gray2 },
		NvimTreeDiagnosticError = { fg = colors.Red12 },
		NvimTreeDiagnosticHint = { fg = colors.Gray12 },
		NvimTreeDiagnosticInformation = { fg = colors.Blue12 },
		NvimTreeDiagnosticWarning = { fg = colors.Orange12 },
		NvimTreeEmptyFolderName = { fg = colors.Blue16 },
		NvimTreeEndOfBuffer = { fg = colors.Gray16 },
		NvimTreeExecFile = { fg = colors.Green16 },
		NvimTreeFileIcon = { fg = colors.Gray16 },
		NvimTreeFileSign = { fg = colors.Gray16 },
		NvimTreeFolderIcon = { fg = colors.Blue16, bold = true },
		NvimTreeFolderName = { fg = colors.Blue16, bold = true },
		NvimTreeFolderSign = { fg = colors.Blue16, bold = true },
		NvimTreeGitDeleted = { fg = colors.Red08 },
		NvimTreeGitDirty = { fg = colors.Orange16 },
		NvimTreeGitIgnored = { fg = colors.Gray08 },
		NvimTreeGitMerge = { fg = colors.Red16 },
		NvimTreeGitNew = { fg = colors.Orchid16 },
		NvimTreeGitRenamed = { fg = colors.Yellow08 },
		NvimTreeGitStaged = { fg = colors.Green16 },
		NvimTreeImageFile = { fg = colors.Magenta16 },
		NvimTreeIndent = { fg = colors.Gray04 },
		NvimTreeLiveFilterBackground = { bg = colors.Gray1 },
		NvimTreeLiveFilterPrefix = { fg = colors.Gray16 },
		NvimTreeLiveFilterValue = { fg = colors.Gray16 },
		NvimTreeMarkdownFile = { fg = colors.Gray16 },
		NvimTreeNormal = { fg = colors.Gray16 },
		NvimTreeOpenedFile = { fg = colors.Gray24 },
		NvimTreeOpenedFileIcon = { fg = colors.Gray24 },
		NvimTreeOpenedFolderName = { fg = colors.Blue16, bold = true },
		NvimTreeRootFolder = { fg = colors.Blue16, bold = true },
		NvimTreeSpecialFile = { fg = colors.Gray16 },
		NvimTreeStatusLine = { fg = colors.Gray16, bg = colors.Gray2 },
		NvimTreeStatusLineNC = { fg = colors.Gray16, bg = colors.Gray2 },
		NvimTreeSymlink = { fg = colors.Cyan16 },
		NvimTreeVertSplit = { fg = colors.Gray04 },
		NvimTreeWinSeparator = { fg = colors.Gray04 },
		NvimTreeWindowPicker = { fg = colors.Gray16, bg = colors.Gray2 },
	}
end
