return function(colors)
	return {
		NvimTreeBookmarkHL = { fg = colors.blue[20] },
		NvimTreeBookmarkIcon = { fg = colors.blue[16], bold = true },
		NvimTreeClosedFolderIcon = { fg = colors.blue[16], bold = true },
		NvimTreeCopiedHL = { fg = colors.green[16] },
		NvimTreeCursorColumn = { bg = colors.gray[1] },
		NvimTreeCursorLine = { bg = colors.gray[1] },
		NvimTreeCursorLineNr = { fg = colors.gray[24], bg = colors.gray[2], bold = true },
		NvimTreeCutHL = { fg = colors.green[12] },
		NvimTreeDiagnosticError = { fg = colors.red[12] },
		NvimTreeDiagnosticErrorFileHL = { fg = colors.red[20] },
		NvimTreeDiagnosticErrorFolderHL = { fg = colors.red[20] },
		NvimTreeDiagnosticErrorIcon = { fg = colors.red[20] },
		NvimTreeDiagnosticHint = { fg = colors.gray[12] },
		NvimTreeDiagnosticHintFileHL = { fg = colors.blue[20] },
		NvimTreeDiagnosticHintFolderHL = { fg = colors.blue[20] },
		NvimTreeDiagnosticHintIcon = { fg = colors.blue[20] },
		NvimTreeDiagnosticInfoFileHL = { fg = colors.blue[20] },
		NvimTreeDiagnosticInfoFolderHL = { fg = colors.blue[20] },
		NvimTreeDiagnosticInfoIcon = { fg = colors.blue[20] },
		NvimTreeDiagnosticInformation = { fg = colors.blue[12] },
		NvimTreeDiagnosticWarnFileHL = { fg = colors.orange[20] },
		NvimTreeDiagnosticWarnFolderHL = { fg = colors.orange[20] },
		NvimTreeDiagnosticWarnIcon = { fg = colors.orange[20] },
		NvimTreeDiagnosticWarning = { fg = colors.orange[12] },
		NvimTreeEmptyFolderName = { fg = colors.blue[12] },
		NvimTreeEndOfBuffer = { fg = colors.gray[16] },
		NvimTreeExecFile = { fg = colors.green[16] },
		NvimTreeFileIcon = { fg = colors.gray[16] },
		NvimTreeFileSign = { fg = colors.gray[16] },
		NvimTreeFolderArrowClosed = { fg = colors.blue[16], bold = true },
		NvimTreeFolderArrowOpen = { fg = colors.blue[16], bold = true },
		NvimTreeFolderIcon = { fg = colors.blue[16], bold = true },
		NvimTreeFolderName = { fg = colors.blue[16], bold = true },
		NvimTreeFolderSign = { fg = colors.blue[16], bold = true },
		NvimTreeGitDeleted = { fg = colors.red[8] },
		NvimTreeGitDeletedIcon = { fg = colors.red[8] },
		NvimTreeGitDirty = { fg = colors.orange[16] },
		NvimTreeGitDirtyIcon = { fg = colors.orange[16] },
		NvimTreeGitFileDeletedHL = { fg = colors.red[8] },
		NvimTreeGitFileDirtyHL = { fg = colors.orange[16] },
		NvimTreeGitFileIgnoredHL = { fg = colors.gray[8] },
		NvimTreeGitFileMergeHL = { fg = colors.red[16] },
		NvimTreeGitFileNewHL = { fg = colors.orchid[16] },
		NvimTreeGitFileRenamedHL = { fg = colors.honey[8] },
		NvimTreeGitFileStagedHL = { fg = colors.green[16] },
		NvimTreeGitFolderDeletedHL = { fg = colors.red[8] },
		NvimTreeGitFolderDirtyHL = { fg = colors.orange[16] },
		NvimTreeGitFolderIgnoredHL = { fg = colors.gray[8] },
		NvimTreeGitFolderMergeHL = { fg = colors.red[16] },
		NvimTreeGitFolderNewHL = { fg = colors.orchid[16] },
		NvimTreeGitFolderRenamedHL = { fg = colors.honey[8] },
		NvimTreeGitFolderStagedHL = { fg = colors.green[16] },
		NvimTreeGitIgnored = { fg = colors.gray[8] },
		NvimTreeGitIgnoredIcon = { fg = colors.gray[8] },
		NvimTreeGitMerge = { fg = colors.red[16] },
		NvimTreeGitMergeIcon = { fg = colors.red[16] },
		NvimTreeGitNew = { fg = colors.orchid[16] },
		NvimTreeGitNewIcon = { fg = colors.orchid[16] },
		NvimTreeGitRenamed = { fg = colors.honey[8] },
		NvimTreeGitRenamedIcon = { fg = colors.honey[8] },
		NvimTreeGitStaged = { fg = colors.green[16] },
		NvimTreeGitStagedIcon = { fg = colors.green[16] },
		NvimTreeHiddenDisplay = { fg = colors.gray[6] },
		NvimTreeHiddenFileHL = { fg = colors.gray[6] },
		NvimTreeHiddenFolderHL = { fg = colors.gray[6] },
		NvimTreeHiddenIcon = { fg = colors.gray[6] },
		NvimTreeImageFile = { fg = colors.rose[16] },
		NvimTreeIndent = { fg = colors.gray[4] },
		NvimTreeIndentMarker = { fg = colors.gray[4] },
		NvimTreeLineNr = { fg = colors.gray[6] },
		NvimTreeLiveFilterBackground = { bg = colors.gray[1] },
		NvimTreeLiveFilterPrefix = { fg = colors.gray[16] },
		NvimTreeLiveFilterValue = { fg = colors.gray[16] },
		NvimTreeMarkdownFile = { fg = colors.gray[16] },
		NvimTreeModifiedFileHL = { fg = colors.orchid[12] },
		NvimTreeModifiedFolderHL = { fg = colors.orchid[12] },
		NvimTreeModifiedIcon = { fg = colors.orchid[12] },
		NvimTreeNormal = { fg = colors.gray[16] },
		NvimTreeNormalFloat = { fg = colors.gray[16] },
		NvimTreeNormalFloatBorder = { fg = colors.gray[2] },
		NvimTreeNormalNC = { fg = colors.gray[16] },
		NvimTreeOpenedFile = { fg = colors.gray[24] },
		NvimTreeOpenedFileIcon = { fg = colors.gray[24] },
		NvimTreeOpenedFolderIcon = { fg = colors.blue[16], bold = true },
		NvimTreeOpenedFolderName = { fg = colors.blue[20], bold = true },
		NvimTreeOpenedHL = { fg = colors.gray[24] },
		NvimTreePopup = { fg = colors.gray[16] },
		NvimTreeRootFolder = { fg = colors.blue[24], bold = true },
		NvimTreeSignColumn = { fg = colors.gray[16] },
		NvimTreeSpecialFile = { fg = colors.gray[16] },
		NvimTreeStatusLine = { fg = colors.gray[16], bg = colors.gray[1] },
		NvimTreeStatusLineNC = { fg = colors.gray[16], bg = colors.gray[1] },
		NvimTreeSymlink = { fg = colors.cyan[16] },
		NvimTreeSymlinkFolderName = { fg = colors.blue[16] },
		NvimTreeSymlinkIcon = { fg = colors.gray[16] },
		NvimTreeVertSplit = { fg = colors.gray[4] },
		NvimTreeWinSeparator = { fg = colors.gray[4] },
		NvimTreeWindowPicker = { fg = colors.gray[16], bg = colors.gray[1] },
	}
end
