return function(colors)
	return {
		["@annotation"] = { fg = colors.rose[18], bold = true },
		["@attribute"] = { fg = colors.rose[18], bold = true },
		["@boolean"] = { fg = colors.wine[12], bold = true },
		["@character"] = { fg = colors.coral[16], bold = true },
		["@character.printf"] = { fg = colors.coral[16], bold = true },
		["@character.special"] = { fg = colors.honey[16], bold = true },
		["@comment"] = { fg = colors.gray[8] },
		["@comment.error"] = { fg = colors.gray[8] },
		["@comment.hint"] = { fg = colors.gray[8] },
		["@comment.info"] = { fg = colors.gray[8] },
		["@comment.note"] = { fg = colors.gray[8] },
		["@comment.todo"] = { fg = colors.gray[8] },
		["@comment.warning"] = { fg = colors.gray[8] },
		["@constant"] = { fg = colors.azure[12] },
		["@constant.builtin"] = { fg = colors.cyan[8] },
		["@constant.macro"] = { fg = colors.capri[12] },
		["@constructor"] = { fg = colors.cyan[8] },
		["@constructor.tsx"] = { fg = colors.cyan[8] },
		["@diff.delta"] = { fg = colors.orange[12] },
		["@diff.minus"] = { fg = colors.red[4] },
		["@diff.plus"] = { fg = colors.blue[16] },
		["@function"] = { fg = colors.blue[16] },
		["@function.builtin"] = { fg = colors.cobalt[8] },
		["@function.call"] = { fg = colors.blue[12] },
		["@function.macro"] = { fg = colors.indigo[12] },
		["@keyword"] = { fg = colors.gray[24], bold = true },
		["@keyword.conditional"] = { fg = colors.rose[18], bold = true },
		["@keyword.coroutine"] = { fg = colors.capri[18], bold = true },
		["@keyword.debug"] = { fg = colors.orchid[18], bold = true },
		["@keyword.directive"] = { fg = colors.cobalt[18], bold = true },
		["@keyword.directive.define"] = { fg = colors.cobalt[18], bold = true },
		["@keyword.exception"] = { fg = colors.red[18], bold = true },
		["@keyword.function"] = { fg = colors.blue[18], bold = true },
		["@keyword.import"] = { fg = colors.raspberry[18], bold = true },
		["@keyword.operator"] = { fg = colors.rose[18], bold = true },
		["@keyword.repeat"] = { fg = colors.orange[18], bold = true },
		["@keyword.return"] = { fg = colors.blue[18], bold = true },
		["@keyword.storage"] = { fg = colors.gray[24], bold = true },
		["@keyword.type"] = { fg = colors.orchid[12], bold = true },
		["@label"] = { fg = colors.gray[24], bold = true },
		["@label.json"] = { fg = colors.mint[12] },
		["@label.toml"] = { fg = colors.mint[12] },
		["@markup"] = { fg = colors.gray[16] },
		["@markup.emphasis"] = { fg = colors.gray[24] },
		["@markup.environment"] = { fg = colors.gray[24] },
		["@markup.environment.name"] = { fg = colors.gray[24] },
		["@markup.heading"] = { fg = colors.gray[16], bold = true },
		["@markup.heading.1"] = { fg = colors.gray[24], bold = true },
		["@markup.heading.2"] = { fg = colors.gray[20], bold = true },
		["@markup.heading.3"] = { fg = colors.gray[16], bold = true },
		["@markup.italic"] = { italic = true },
		["@markup.link"] = { fg = colors.gray[12] },
		["@markup.link.label"] = { fg = colors.gray[16] },
		["@markup.link.label.symbol"] = { fg = colors.yellow[16] },
		["@markup.link.url"] = { fg = colors.blue[16] },
		["@markup.list"] = { fg = colors.gray[16] },
		["@markup.list.checked"] = { fg = colors.lime[12] },
		["@markup.list.markdown"] = { fg = colors.amethyst[8] },
		["@markup.list.unchecked"] = { fg = colors.gray[12] },
		["@markup.math"] = { fg = colors.yellow[16] },
		["@markup.raw"] = { fg = colors.gray[24] },
		["@markup.raw.markdown_inline"] = { fg = colors.gray[24] },
		["@markup.strikethrough"] = { strikethrough = true },
		["@markup.strong"] = { bold = true },
		["@markup.underline"] = { underline = true },
		["@method"] = { fg = colors.blue[16] },
		["@method.call"] = { fg = colors.blue[12] },
		["@module"] = { fg = colors.raspberry[12] },
		["@module.builtin"] = { fg = colors.rose[8] },
		["@namespace.builtin"] = { fg = colors.rose[16], bold = true },
		["@none"] = { fg = colors.gray[16] },
		["@number"] = { fg = colors.orange[16] },
		["@number.float"] = { fg = colors.yellow[16] },
		["@operator"] = { fg = colors.rose[18], bold = true },
		["@property"] = { fg = colors.mint[12] },
		["@property.class"] = { fg = colors.mint[12] },
		["@punctuation.bracket"] = { fg = colors.cyan[8] },
		["@punctuation.delimiter"] = { fg = colors.gray[18] },
		["@punctuation.special"] = { fg = colors.rose[18] },
		["@string"] = { fg = colors.red[8] },
		["@string.documentation"] = { fg = colors.red[12] },
		["@string.escape"] = { fg = colors.red[16] },
		["@string.regexp"] = { fg = colors.coral[12] },
		["@string.special.url"] = { fg = colors.red[16], underline = true },
		["@tag"] = { fg = colors.gray[24], bold = true },
		["@tag.attribute"] = { fg = colors.aqua[12] },
		["@tag.attribute.tsx"] = { fg = colors.aqua[12] },
		["@tag.builtin"] = { fg = colors.gray[24], bold = true },
		["@tag.delimiter"] = { fg = colors.cyan[8] },
		["@tag.delimiter.tsx"] = { fg = colors.cyan[8] },
		["@tag.javascript"] = { fg = colors.gray[24], bold = true },
		["@tag.tsx"] = { fg = colors.gray[24], bold = true },
		["@type"] = { fg = colors.orchid[12] },
		["@type.builtin"] = { fg = colors.magenta[8] },
		["@type.definition"] = { fg = colors.amethyst[16] },
		["@type.qualifier"] = { fg = colors.amethyst[12] },
		["@variable"] = { fg = colors.aqua[12] },
		["@variable.builtin"] = { fg = colors.sky[8] },
		["@variable.member"] = { fg = colors.mint[12] },
		["@variable.parameter"] = { fg = colors.aqua[12] },
		["@variable.parameter.builtin"] = { fg = colors.sky[8] },
	}
end
