#!/bin/sh

monocle() {
    hyprctl keyword general:layout monocle
}

case "$1" in
    "scrolling")
        monocle
        hyprctl keyword general:gaps_in 8
        case "$2" in
            "33%")
                hyprctl keyword scrolling:column_width 0.33
                ;;
            "100%")
                hyprctl keyword scrolling:column_width 1.00
                ;;
            *)
                hyprctl keyword scrolling:column_width 0.50
                ;;
        esac
        hyprctl keyword general:layout scrolling
        ;;
    "dwindle")
        hyprctl keyword general:gaps_in 4
        hyprctl keyword general:layout dwindle
        ;;
    "master")
        hyprctl keyword general:gaps_in 4
        hyprctl keyword general:layout master
        ;;
    *)
        monocle
        ;;
esac

