#!/bin/sh

pgrep wvkbd-mobintl || wvkbd-mobintl -H 384 -L 384 -R 16 -alpha 148 --fn "Ubuntu Sans Mono Bold 10" --bg "#131313" --fg "#ededed" --fg-sp "#949494" --press "#1a1a1a" --press-sp "#1a1a1a" --swipe "#212121" --swipe-sp "#292929" --text "#ededed" --text-sp "#949494" -l simple,cyrillic,emoji
