#!/bin/sh

HELPER="$HOME/.config/waybar/module/helper"

case "$1" in
    "get")
         pgrep -x "hyprsunset" > /dev/null \
             && $HELPER/jsonify "on" \
             || $HELPER/jsonify "off"
         ;;
    "toggle")
        pkill -x hyprsunset || hyprsunset -t 2000 > /dev/null 2>&1
        pkill -RTMIN+7 waybar
        ;;
    *)
        echo "?"
        ;;
esac
