#!/bin/sh

get_random_shimeji() {
    shimejictl list | grep '^[0-9]' | shuf -n 1
}

ITEM="$(get_random_shimeji)"
NAME="${ITEM#*:}"

case $1 in
    on)
        shimejictl summon "$NAME"
        ;;
    off)
        pkill shimeji-overlay
        ;;
    toggle)
        pkill shimeji-overlay || shimejictl summon "$NAME"
        ;;
    *)
        echo "?"
        ;;
esac

