#!/bin/sh

SHADERS="$HOME/.config/hypr/shaders"

reset() {
        killall waybar
        killall waypaper
        killall mpvpaper
}

restore() {
        hyprctl reload &
        waypaper --restore &
}

case "$1" in
    "cartoon")
        reset
        restore

        waybar > /dev/null 2>&1 &

        hyprctl keyword decoration:screen_shader "$SHADERS/vivid.glsl"

        hyprctl keyword animation "windows, 1, 5, easeOutExpo, popin"
        hyprctl keyword animation "windowsIn, 1, 8, easeOutCubic, slide top"
        hyprctl keyword animation "windowsOut, 1, 3, easeInCubic, slide bottom"
        hyprctl keyword animation "windowsMove, 1, 13, easeOutBack"

        hyprctl keyword animation "layers, 1, 5, easeOutSine, fade"
        hyprctl keyword animation "layersIn, 1, 5, easeOutSine, fade"
        hyprctl keyword animation "layersOut, 1, 5, easeInSine, fade"

        hyprctl keyword animation "fade, 1, 8, easeOutQuadratic"
        hyprctl keyword animation "fadeIn, 1, 3, easeOutQuadratic"
        hyprctl keyword animation "fadeOut, 1, 8, easeInSine"
        hyprctl keyword animation "fadeSwitch, 1, 8, easeOutQuadratic"
        hyprctl keyword animation "fadeShadow, 1, 8, easeOutQuadratic"
        hyprctl keyword animation "fadeDim, 1, 2, easeOutSine"
        hyprctl keyword animation "fadeLayers, 1, 5, easeOutQuadratic"
        hyprctl keyword animation "fadeLayersIn, 1, 5, easeOutQuadratic"
        hyprctl keyword animation "fadeLayersOut, 1, 8, easeInSine"
        hyprctl keyword animation "fadePopups, 1, 5, easeOutQuadratic"
        hyprctl keyword animation "fadePopupsIn, 1, 5, easeOutQuadratic"
        hyprctl keyword animation "fadePopupsOut, 1, 2, easeInSine"
        hyprctl keyword animation "fadeDpms, 1, 8, easeOutQuadratic"

        hyprctl keyword animation "border, 1, 5, easeOutSine"
        hyprctl keyword animation "borderangle, 1, 5, easeOutSine"

        hyprctl keyword animation "workspaces, 1, 8, linear"
        hyprctl keyword animation "workspacesIn, 1, 13, easeOutCubic"
        hyprctl keyword animation "workspacesOut, 1, 8, easeOutCubic"

        hyprctl keyword animation "specialWorkspace, 1, 2, linear, fade"
        hyprctl keyword animation "specialWorkspaceIn, 1, 5, easeOutBack, fade"
        hyprctl keyword animation "specialWorkspaceOut, 1, 3, easeInSine, fade"

        hyprctl keyword animation "zoomFactor, 1, 3, easeOutQuint"
        hyprctl keyword animation "monitorAdded, 1, 8, easeOutBack"
        ;;
    "mono")
        reset
        restore

        waybar > /dev/null 2>&1 &

        hyprctl keyword general:layout monocle
        ;;
    "focus")
        reset
        restore

        hyprctl keyword decoration:screen_shader ""

        hyprctl keyword decoration:inactive_opacity 0.88
        hyprctl keyword decoration:shadow:enabled false

        hyprctl keyword animations:enabled false

        hyprctl keyword general:layout monocle
        ;;

    "void")
        reset

        hyprctl keyword decoration:screen_shader ""

        hyprctl keyword decoration:inactive_opacity 0.88
        hyprctl keyword decoration:shadow:enabled false

        hyprctl keyword animations:enabled false
        hyprctl keyword decoration:blur:enabled false

        hyprctl keyword general:gaps_in 0
        hyprctl keyword general:gaps_out 0
        hyprctl keyword general:border_size 0

        hyprctl keyword decoration:rounding 0

        hyprctl keyword decoration:rounding_power 0

        hyprctl keyword decoration:fullscreen_opacity 1
        hyprctl keyword decoration:active_opacity 1
        hyprctl keyword decoration:inactive_opacity = 1

        hyprctl keyword general:layout monocle
        ;;
    *)
        reset
        restore

        waybar > /dev/null 2>&1 &
        ;;
esac



