[main]
start-hidden=false
searchbar=false
icon-size=96
dock-icon-size=96
app-margins=64
name-under-icon=true
scroll-bars=false
name-length=16
items-per-row=4
anchors=top right bottom left
monitor=0
layer-shell=true
dock-items=
animation-duration=200
use-uwsm=true
history-size=3
