$hyper = HYPER_L
$modifier = SUPER
$modifierLeft = SUPER_L

$alternate = ALT
$alternateLeft = ALT_L
$alternateRight = ALT_R

$control = CTRL
$controlLeft = CTRL_L
$controlRight = CTRL_R

$shift = SHIFT
$shiftLeft = SHIFT_L
$shiftRight = SHIFT_R

$mouseClickLeft = mouse:272
$mouseClickMiddle = mouse:274
$mouseClickRight = mouse:273
$mouseScrollUp = Mouse_Up
$mouseScrollDown = Mouse_Down

$power = XF86PowerOff

$brightnessUp = XF86MonBrightnessUp
$brightnessDown = XF86MonBrightnessDown

$volumeMute = XF86AudioMute
$volumeUp = XF86AudioRaiseVolume
$volumeDown = XF86AudioLowerVolume

$script = $HOME/.config/hypr/script
$shader = $HOME/.config/hypr/shaders
