$hyper = HYPER_L
$modifier = SUPER
$modifierLeft = SUPER_L

$power = XF86PowerOff

$brightnessUp = XF86MonBrightnessUp
$brightnessDown = XF86MonBrightnessDown

$volumeMute = XF86AudioMute
$volumeUp = XF86AudioRaiseVolume
$volumeDown = XF86AudioLowerVolume

$script = $HOME/.config/hypr/script
$shader = $HOME/.config/hypr/shaders
