windowrule {
    name = float
    match:float = true
    animation = fade
}

windowrule {
    name = zenity
    match:class = zenity
    dim_around = on
}

windowrule {
    name = screensaver
    match:title = cmatrix
    animation = fade 100%
    dim_around = on
    float = true
    fullscreen = true
}

windowrule {
    name = calculator
    match:class = org.gnome.Calculator
    animation = slide
    float = true
    pin = true
}

windowrule {
    name = waypaper
    match:class = waypaper
    animation = slide
    float = true
    pin = true
}

windowrule {
    name = dialect
    match:class = app.drey.Dialect
    animation = slide
    float = true
    pin = true
}

windowrule {
    name = coulr
    match:class = com.github.finefindus.eyedropper
    float = true
    pin = true
    animation = slide
}

windowrule {
    name = histui
    match:class = kitty
    match:title = histui
    float = true
    pin = true
    dim_around = on
}

windowrule {
    name = firefox
    match:class = firefox
}

