windowrule {
    name = float
    match:float = true
    animation = fade
}

windowrule {
    name = calculator
    match:class = org.gnome.Calculator
    animation = slide
    float = true
    pin = true
}

windowrule {
    name = characters
    match:class = org.gnome.Characters
    float = true
    pin = true
    animation = slide
}

windowrule {
    name = coulr
    match:class = com.github.finefindus.eyedropper
    float = true
    pin = true
    animation = slide
}

windowrule {
    name = dialect
    match:class = app.drey.Dialect
    animation = slide
    float = true
    pin = true
}

windowrule {
    name = histui
    match:class = kitty
    match:title = histui
    float = true
    pin = true
    dim_around = on
}

windowrule {
    name = rnote
    match:class = com.github.flxzt.rnote
    fullscreen = true
    workspace = special:stylus
}

windowrule {
	name = shimeji
	match:class = shimeji
	float = true
	no_blur = true
	no_focus = true
	no_shadow = true
	border_size = 0
}


windowrule {
    name = stylus
    match:workspace = special:stylus 
    fullscreen = true
}

windowrule {
    name = zenity
    match:class = zenity
    above_lock = 2
    dim_around = on
}

windowrule {
    name = unimatrix
    match:class = unimatrix
    border_size = 0
    dim_around = on
    focusonactivate = true
    fullscreen = true
    no_anim = true
    pin = true
    rounding = 0
}

windowrule {
    name = waypaper
    match:class = waypaper
    animation = slide
    float = true
    pin = true
}

windowrule {
    name = weather
    match:class = org.gnome.Weather
    animation = slide
    float = true
    pin = true
    size = 960 640
}

windowrule {
    name = clock
    match:class = org.gnome.clocks
    animation = slide
    float = true
    pin = true
    size = 960 640
}
