workspace = , persistent:false

workspace = special, layout:monocle

workspace = special:stylus, layout:monocle
workspace = special:radio, layout:monocle

workspace = speical:ekam, layout:dwindle
workspace = speical:dva, layout:dwindle
workspace = speical:trini, layout:dwindle
workspace = speical:chatvari, layout:dwindle
workspace = speical:pancha, layout:dwindle
workspace = speical:shat, layout:dwindle
workspace = speical:sapta, layout:dwindle
workspace = speical:ashta, layout:dwindle
workspace = speical:nava, layout:dwindle
workspace = speical:shunya, layout:dwindle
