workspace = , persistent:false

workspace = special, layout:monocle

workspace = special:stylus, layout:monocle
workspace = special:radio, layout:monocle

workspace = special:ekam, layout:dwindle
workspace = special:dva, layout:dwindle
workspace = special:trini, layout:dwindle
workspace = special:chatvari, layout:dwindle
workspace = special:pancha, layout:dwindle
workspace = special:shat, layout:dwindle
workspace = special:sapta, layout:dwindle
workspace = special:ashta, layout:dwindle
workspace = special:nava, layout:dwindle
workspace = special:shunya, layout:dwindle
